const creativeTopics = [
  // 🎨 Fun & Whimsical
  "A picnic on the moon",
  "The secret life of houseplants",
  "When coffee dreams of adventure",
  "A city made of candy",
  "Rainy days in a robot's world",
  "A love letter from a lost sock",
  "When animals run the internet",
  "A fairytale told by a toaster",
  "Midnight in a neon jungle",
  "Conversations between clouds",
  "A superhero with zero powers but lots of snacks",
  "The future of flying bicycles",
  "A world where time moves backward",
  "Dreams stored in mason jars",
  "A cafe where feelings are served as drinks",

  // 🧠 Thought-Provoking & Minimalist
  "The sound of silence",
  "What does home feel like?",
  "A moment that changed everything",
  "Minimalism in a noisy world",
  "The beauty of ordinary things",
  "When nature reclaims the city",
  "The space between words",
  "Time as a loop, not a line",
  "Connection in the digital age",
  "Shadows and light: a study in contrast",
  "The poetry of movement",
  "What we leave behind",
  "Emotions as colors",
  "A world with no mirrors",
  "Finding stillness in chaos",

  // 🌼 Seasonal
  "First signs of spring",
  "Autumn whispers through the trees",
  "A snow day in a quiet town",
  "Summer through a child’s eyes",
  "The scent of rain in July",
  "Festivals of light around the world",
  "A walk through winter silence",
  "When seasons blend into one",

  // 📼 Nostalgic
  "Rewinding a VHS tape of childhood",
  "Sunday mornings in the 90s",
  "The magic of handwritten letters",
  "Your first best friend",
  "A box of forgotten treasures",
  "That one summer that felt infinite",
  "Waiting for dial-up internet to connect",
  "The last page of a childhood diary",

  // 🚀 Futuristic
  "A day in the life of a space tourist",
  "Love in a world run by AI",
  "Cities that float in the sky",
  "Digital memories you can feel",
  "A library of future dreams",
  "Dinner printed by a food 3D printer",
  "Fashion in 2095",
  "Virtual nature for screen-bound souls",

  // 🧘‍♀️ Generic & Open-Ended
  "A day in my life",
  "My dream destination",
  "What happiness looks like",
  "The future I imagine",
  "A world without technology",
  "The power of kindness",
  "My safe space",
  "A walk in the park",
  "Things I can't live without",
  "How I stay inspired",
  "Colors that describe me",
  "If I could talk to my past self",
  "The feeling of freedom",
  "A letter to the world",
  "When I feel most alive",
  "The beauty of routine",
  "Magic in the mundane",
  "What peace means to me",
  "Little joys in life",
  "A story told through colors",

  // 🔍 Research-Friendly Topics
  "Roman Architecture 🏛️",
  "Evergreen Forests",
  "Coffee: From Bean to Brew",
  "The Solar System",
  "Ancient Egyptian Culture",
  "The History of Animation",
  "Coral Reefs & Marine Life",
  "Space Exploration",
  "The Lifecycle of a Butterfly",
  "Volcanoes and How They Form",
  "The Science of Rainbows",
  "Renewable Energy Sources",
  "Mountains Around the World",
  "The History of Writing Systems",
  "How the Internet Works",
  "Cloud Types & Weather Patterns",
  "Global Cuisines: A Taste Tour",
  "The Human Brain",
  "Wildlife in the African Savannah",
  "Traditional Clothing Around the World",
  "Types of Art Movements",
  "Ocean Currents & Climate",
  "The Life of a Honeybee",
  "Historical Landmarks Around the World",
  "Music Genres Across Cultures",
   // 🛌 Sleep & Rest
  "The science of dreams",
  "Power naps: friend or foe?",
  "The perfect bedtime routine",
  "What if we never slept?",
  "How sleep affects creativity",

  // 📖 Study & Learning
  "Study patterns that actually work",
  "Active recall vs passive learning",
  "How to beat procrastination",
  "Creating your ideal study space",
  "Learning styles: myth or magic?",

  // 🥗 Food
  "Comfort foods across cultures",
  "The psychology of taste",
  "Food trends on social media",
  "The future of plant-based eating",
  "Street food stories",

  // 🌌 Sky & Space
  "The night sky and its constellations",
  "Why we love watching sunsets",
  "The changing colors of the sky",
  "Weather patterns explained",
  "Northern Lights: Earth’s natural light show",

  // 🌱 Plants & Nature
  "Plants that thrive on neglect",
  "The language of flowers",
  "Urban gardening for beginners",
  "The role of trees in climate control",
  "How plants communicate",

  // 🎨 Hobbies
  "Why everyone needs a hobby",
  "The rise of DIY culture",
  "How hobbies improve mental health",
  "Collecting vs creating",
  "Turning hobbies into side hustles",

  // 🎓 Learning & Growth
  "Lifelong learning in the digital age",
  "What school didn’t teach me",
  "Microlearning for busy lives",
  "Learning through failure",
  "Building curiosity muscles",

  // 📈 Marketing
  "Emotional branding 101",
  "What makes content go viral?",
  "The power of storytelling in marketing",
  "Influencer marketing: a deep dive",
  "User psychology in digital campaigns",

  // 💻 Coding & Tech
  "What is clean code?",
  "The history of programming languages",
  "The magic behind mobile apps",
  "Why UX/UI design matters",
  "From bug to fix: debugging explained",

  // 🔬 Science
  "Why do we yawn?",
  "The chemistry of emotions",
  "How vaccines work",
  "The human body's hidden systems",
  "Science behind colors we see",

  // ➗ Math
  "How math appears in nature",
  "The beauty of symmetry",
  "Famous unsolved math problems",
  "Math in architecture",
  "Everyday problems math secretly solves",

    // 🌙 Sleep & Rest
  "🛏️ Why do we dream?",
  "🌜 Sleep cycles explained",
  "🧸 What makes a good bedtime story?",
  "😴 Sleep hygiene for busy minds",
  "🕯️ Nighttime rituals around the world",

  // 📚 Study & Learning
  "📚 Study hacks that actually work",
  "🧠 How your brain memorizes things",
  "🔁 Is repetition the key to mastery?",
  "✏️ Mind-mapping for clarity",
  "🎧 Music vs silence while studying",

  // ☕ Food & Drink
  "🍕 History of your favorite snacks",
  "🍫 How chocolate became a global treat",
  "🍵 Tea vs coffee: culture and science",
  "🥗 The rise of clean eating",
  "🌶️ Spices that shaped history",

  // 🌌 Sky & Weather
  "🌠 The stars we named and why",
  "⛅ How clouds are formed",
  "🌤️ What's your sky mood today?",
  "☀️ Ancient sun myths",
  "🌙 Moon phases & their meanings",

  // 🌿 Plants & Nature
  "🪴 Houseplants that heal",
  "🌵 Surviving like a cactus",
  "🌳 The wisdom of old trees",
  "🍄 Forest floors and hidden life",
  "🌻 Why we give flowers",

  // 🎨 Hobbies & Personal Expression
  "🧶 Crafting as meditation",
  "📸 Photography through your own lens",
  "🧩 The joy of puzzles",
  "🎮 Are video games a modern art form?",
  "📖 Reading slumps & how to escape them",

  // 🧑‍🏫 Lifelong Learning
  "🔎 Curiosity as a superpower",
  "🎯 How to set learning goals that stick",
  "💡 Learning in the age of distraction",
  "📱 EdTech tools to explore",
  "📝 Journaling to learn better",

  // 📢 Marketing & Business
  "💬 Brand voice: why it matters",
  "📈 Storytelling in ads",
  "🛍️ The psychology of colors in marketing",
  "🤖 AI in marketing: threat or tool?",
  "📲 How trends go viral",

  // 💻 Coding & Tech
  "🔍 Algorithms in everyday life",
  "🧱 What is an API (and why should I care)?",
  "👨‍💻 Coding logic puzzles",
  "💡 Frontend vs backend: explained simply",
  "🕸️ The web: what really happens when you click",

  // 🔬 Science & Curiosity
  "🧬 DNA: The original blueprint",
  "🦠 Microbes we can’t live without",
  "🔥 The science of fire",
  "🧪 Accidental discoveries that changed science",
  "⚛️ Why atoms matter",

  // ➗ Math & Logic
  "📐 Geometry in nature",
  "🔢 The Fibonacci sequence in real life",
  "🧠 Logical fallacies explained",
  "🧩 Math puzzles for all ages",
  "📊 Why graphs help us think clearer",

   "🧃 A day in the life of your favorite drink",
  "🎒 What's in your bag?",
  "🎧 The soundtrack to your life",
  "🎂 A letter to your past or future self on your birthday",
  "💬 Quotes that shaped you",
  "💌 A letter you never sent",
  "🚪 What’s behind the mystery door?",
  "📅 If you could relive one day",
  "📍 A place that changed you",
  "🔦 Things that make you feel seen",
  
  "🕰️ The beauty of waiting",
  "🧸 A memory tied to a smell",
  "📖 If your life were a book, what’s the title?",
  "🧳 What would you pack for a spontaneous trip?",
  "🪞 A mirror’s perspective",
  "🎨 If emotions were colors",
  "🧭 The map of your mind",
  "🧵 The threads that tie you to home",
  "📼 Recreate a memory like a movie scene",
  "🕊️ A moment you felt free",

  "🪄 Everyday magic moments",
  "🎠 A dream you had (or want to have)",
  "🧃 The taste of nostalgia",
  "🔑 What would your dream room look like?",
  "📺 If your day was a Netflix episode",
  "🎈 What makes you feel like a kid again?",
  "🪁 A sky full of metaphors",
  "🫧 What does peace look like to you?",
  "🗺️ A travel destination from your imagination",
  "🎉 A tradition you invented or want to start",

  "📎 A desk that tells a story",
  "🥽 Try something new: document the chaos",
  "🎭 A day wearing a different identity",
  "🔮 If you could see one version of the future",
  "📚 A book you want to live inside",
  "🫀 Your heart as a city",
  "🌍 If the world could talk",
  "📦 What’s in your ‘mind attic’?",
  "🌸 A season that best represents you",
  "🧠 A thought that changed your mind",
   "😊 What happiness means to me",
  "🌼 Learning to slow down",
  "🍂 Letting go gracefully",
  "🫶 The power of kindness",
  "🌻 Little things that bring joy",
  "🌙 Finding calm in the chaos",
  "🪞 How I see myself vs how others see me",
  "💭 Thoughts I wish I could quiet",
  "💫 Embracing uncertainty",
  "🧘‍♀️ A moment I felt truly present",
  
  "💡 A lesson I learned the hard way",
  "🌊 Going with the flow",
  "❤️ Learning to love yourself",
  "📖 A story I’m still writing",
  "🍃 Moments of stillness",
  "🎈 Letting your inner child play",
  "🚶 A walk that changed my perspective",
  "🎁 Finding beauty in the ordinary",
  "🪄 Rediscovering wonder",
  "🪶 Lightness vs heaviness in everyday life",

  "🕰️ Time I wish I could slow down",
  "🗣️ Words that stayed with me",
  "🎨 Creating just for me",
  "🌤️ A new beginning",
  "📦 What I’m learning to unlearn",
  "📶 Disconnecting to reconnect",
  "🎢 The highs and lows of growth",
  "💐 Being soft in a hard world",
  "🎯 Redefining success",
  "🌱 The art of starting over",

  "💔 Healing isn’t linear",
  "🧩 Putting the pieces back together",
  "🫂 Giving yourself grace",
  "🩹 What healing looks like for me",
  "🌦️ The storm I survived",
  "🥀 Letting go of who I used to be",
  "🪴 Growing through what I went through",
  "🌙 Nights that taught me something",
  "🚪 When one door closes...",
  "🫧 Finding softness in hard moments",

    "🚀 The version of me I’m working toward",
  "🧠 A mindset that changed everything",
  "🔥 What keeps me going",
  "📍 Where I started vs where I am",
  "🌄 My dream life, in detail",
  "🎯 Learning to trust the process",
  "🧗‍♂️ Pushing past limits",
  "🔄 Failing forward",
  "🎓 A lesson school never taught me",
  "⏳ I’m not behind, I’m on my timeline",

    "🪞 Who am I becoming?",
  "🧬 The pieces that make me, me",
  "🎭 The masks I wear",
  "🖼️ How I want to be remembered",
  "📖 Writing my own story",
  "🧳 What I carry with me",
  "🔍 Finding myself again",
  "🌱 Who I was, who I am, who I will be",
  "🔓 Becoming more of myself",
  "🧵 Untangling my identity",

    "📼 A memory I keep replaying",
  "📻 The sound of my childhood",
  "🍪 Smells that take me back",
  "🏠 What home used to feel like",
  "🌆 A place I miss",
  "🛝 When life felt simple",
  "🧸 My favorite comfort object",
  "🌈 What I wish I could tell my younger self",
  "📸 Life before the filters",
  "📓 A page from my past",

   "🛠️ Building myself back up",
  "🛡️ What bravery looks like",
  "💪 A time I surprised myself",
  "🔥 Rising from burnout",
  "🧱 The walls I broke through",
  "⚔️ Fighting for peace of mind",
  "🏃‍♀️ Choosing progress over perfection",
  "🌋 Staying grounded through chaos",
  "💬 Speaking up for myself",
  "🚧 I’m still under construction",

    "☕ The ritual of your morning coffee",
  "🌿 The plant that matches your energy",
  "📚 Study tips that actually work",
  "🌌 Looking up at the night sky",
  "💤 Why rest is productive",
  "🎓 What school never taught you",
  "🧠 The way your brain organizes chaos",
  "🍲 A recipe that reminds you of home",
  "📓 The way you study best",
  "🌧️ When the weather matches your mood",

  "🖋️ A letter to your future self",
  "🌳 Forests and the stories they hold",
  "👩‍💻 What coding taught me about life",
  "🧪 Science is all around you",
  "📐 Life lessons from math class",
  "🪐 If you lived on another planet",
  "🗺️ Your dream study destination",
  "🛌 How to create a perfect sleep sanctuary",
  "🌅 Learning to slow down at sunset",
  "🏞️ Nature as your classroom",

  "🎮 What video games taught me",
  "📖 Your life as a study guide",
  "🚀 Hacking your attention span",
  "🌼 What hobbies teach you about yourself",
  "🧃 Fueling your body, feeding your brain",
  "📊 Data as a storytelling tool",
  "🎵 A playlist that boosts focus",
  "🍃 Learning in moments of stillness",
  "🧩 Piecing together your ideal routine",
  "🎯 Study like a strategist, not a machine",

  "🕹️ If learning was a video game",
  "🍵 A cozy space to just be",
  "📦 What’s in your brain dump box?",
  "🫖 Tea vs Coffee: what’s your creative fuel?",
  "🎈 Your study style as a personality",
  "🧘‍♀️ The art of intentional laziness",
  "🏕️ A weekend away from screens",
  "🪴 How you nurture your focus",
  "📺 Your life as a Netflix mini doc",
  "🌠 Ideas that keep you up at night",

    "💾 Life before the cloud",
  "🤖 How AI sees the world",
  "🧠 Your brain as a computer",
  "⚡ A world without Wi-Fi",
  "🖥️ What your desktop says about you",
  "🧬 Tech that changed your life",
  "📱 A timeline of your phones",
  "🔐 Passwords we wish we could remember",
  "🛰️ If satellites could talk",
  "🪄 Magic vs Machine: where’s the line?",

  "🕹️ Tech nostalgia: growing up digital",
  "📶 Offline is the new luxury",
  "📊 Data is not just numbers",
  "🎮 Gamify your life",
  "📷 The evolution of selfies",
  "🧯 Tech fails that taught you something",
  "🖨️ The weirdness of printers",
  "🔧 Fixing the bugs in real life",
  "🎧 Headphones in = world off",
  "👾 If the internet had feelings",

  "🌐 Building your digital identity",
  "📲 Apps you can’t live without",
  "🧠 If you could download a skill",
  "🧰 Coding your dream tool",
  "📡 Old tech with a new twist",
  "🛠️ DIY tech hacks that actually work",
  "📤 The joy of hitting 'send'",
  "🔍 Searching for meaning (on Google)",
  "🖱️ Clicks that changed everything",
  "⌚ Your life, tracked by a smartwatch",

  "👨‍💻 A day in the life of your code",
  "💡 Tech ideas the world still needs",
  "📟 Vintage tech reimagined",
  "🚫 When to log off (and why)",
  "🔋 If you had a battery percentage",
  "📂 Organize your digital mess",
  "🪫 Low power mode for the brain",
  "📡 Future tech you can’t wait for",
  "🎛️ Design like a developer",
  "💬 Tech conversations we should be having",

   "🌿 Finding beauty in the basics",
  "🌻 A day without distractions",
  "🌊 What water teaches us",
  "🌱 The joy of growing something slowly",
  "🍞 Your life as a slow recipe",
  "🏞️ A walk that brought you peace",
  "🌾 Noticing the unnoticed",
  "🕊️ What it means to live gently",
  "🍂 Lessons from falling leaves",
  "🌤️ How the weather reflects your mood",

  "🪨 The stillness of stone",
  "🌳 Trees and their quiet wisdom",
  "🐚 Collecting small joys",
  "🔥 The comfort of firelight",
  "🍯 Life in warm tones",
  "🛏️ Morning routines that don’t rush",
  "🎐 The sound of silence",
  "🍋 Bittersweet and beautiful",
  "🧺 Chores as rituals",
  "🌙 Moon phases and mood swings",

  "🪺 Building a cozy life",
  "🌼 Nature’s tiny miracles",
  "🧭 Living by your own rhythm",
  "🌵 Learning to thrive in hard places",
  "🍃 Resting like the earth",
  "🌻 A season you relate to",
  "⛺ What slow living means to you",
  "🚲 Your life at walking speed",
  "🧘‍♀️ A moment you felt light",
  "🌺 The color of calm",

  "📦 Letting go of things that own you",
  "🏔️ The silence of high places",
  "🕯️ Lighting a slower kind of life",
  "🐦 The freedom of birds",
  "🍵 A warm drink, a quiet morning",
  "🌿 Simplicity as a form of rebellion",
  "🍃 A breath of fresh air",
  "🪷 Still water runs deep",
  "🧤 Softness as strength",
  "🌦️ Weathering seasons of change",

];

export {creativeTopics};
